#
# Unmount the set of ais_devices on the set of hosts ais_hosts (variables to
# be specified on cmdline), and remove their fstab entries.
#
---
- hosts: "{{ ais_hosts }}"
  vars_files:
    - "vars.yml"

  gather_facts: true
  roles:
          - { role: ais_datafs, ais_fs_umount_purge: true }

