apiVersion: v1
kind: Service
metadata:
  name: ais-proxy
  labels:
    app: ais
    type: proxy
  annotations:
    kapp.k14s.io/change-group: "setup"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    type: proxy
  ports:
    - name: public
      port: 8080
    - name: control
      port: 9080
    - name: data
      port: 10080
