- name: Copy aisloader binary to hosts
  hosts: aisloader_hosts
  become: true
  tasks:
    - name: Copy aisloader binary
      ansible.builtin.copy:
        src: "{{ aisloader_path }}"
        dest: /usr/local/bin/aisloader
    - name: Grant rwx permissions to /usr/local/bin/aisloader
      ansible.builtin.file:
        path: /usr/local/bin/aisloader
        mode: 'a+x'
