- name: Run aisloader "{{ bench_type }}" on bucket {{ bucket }}
  hosts: aisloader_hosts
  gather_facts: no
  vars_files:
    - "vars/bench.yaml"

  tasks:
  - name: Set ansible fact for ips of target hosts
    set_fact:
      target_host_ips: "{{ groups['target_hosts'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"

  - name: Copy object list if provided
    ansible.builtin.copy:
      src: "{{ filelist }}"
      dest: "{{ filelist | basename }}"
    when: filelist is defined and filelist | length > 0

  - name: Start aisloader direct GET
    ansible.builtin.script: scripts/aisloader_script.sh --bench_type={{ bench_type }} --s3_endpoint={{ s3_endpoint }} --bucket={{ bucket }} --duration={{ duration }} --grafana_host={{ hostvars[grafana_host].ansible_host }} --workers={{ get_workers.value }} --filelist={{ filelist | basename }}
    when: bench_type == "direct_get"

  - name: Start aisloader direct PUT
    ansible.builtin.script: scripts/aisloader_script.sh --bench_type={{ bench_type }} --s3_endpoint={{ s3_endpoint }} --bucket={{ bucket }} --each_size={{ bench_size }} --total_size={{ total_size }} --grafana_host={{ hostvars[grafana_host].ansible_host }} --workers={{ put_workers.value }}
    when: bench_type == "direct_put"

  - name: Start aisloader GET
    ansible.builtin.script: scripts/aisloader_script.sh --bench_type={{ bench_type }} --bucket={{ bucket }} --ais_proxies={{ target_host_ips }} --ais_port={{ ais_port.value }} --duration={{ duration }} --grafana_host={{ hostvars[grafana_host].ansible_host }} --workers={{ get_workers.value }} --filelist={{ filelist | basename }}
    when: bench_type == "get"

  - name: Start aisloader PUT
    ansible.builtin.script: scripts/aisloader_script.sh --bench_type={{ bench_type }} --bucket={{ bucket }} --ais_proxies={{ target_host_ips }} --ais_port={{ ais_port.value }} --each_size={{ bench_size }} --total_size={{ total_size }} --grafana_host={{ hostvars[grafana_host].ansible_host }} --workers={{ put_workers.value }}
    when: bench_type == "put"

  - name: Set bucket_name variable
    set_fact:
      bucket_name: "{{ bucket if '//' not in bucket else bucket.split('//')[1] }}"

  - name: Find the output files
    find:
      paths: /tmp/aisloader/
      patterns: "{{ bucket_name }}-{{ bench_type }}*" 
      use_regex: False
    register: outfiles

  - name: Fetch the output files from remote
    fetch:
      src: "{{ item.path }}"
      dest: ../output/{{ bench_type }}/{{ bucket_name }}/
      flat: yes
    with_items: "{{ outfiles.files }}"