- name: Install Docker on defined hosts
  hosts: "{{ hosts }}"
  become: true
  gather_facts: no
  vars: 
    os_version: CentOS_8
    crio_version: 1.28

  tasks:
    - name: Install required system packages for Docker
      dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - python3-dnf
        - device-mapper-persistent-data
        - lvm2
        - dnf-utils
        - zip
        - unzip

    - name: Set up Docker repository
      command: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"

    - name: Set up repo for libcontainers
      command: "curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os_version }}/devel:kubic:libcontainers:stable.repo"
      
    - name: Set up repo for cri-o
      command: "curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/{{ os_version }}/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.repo"

    - name: Install the latest runc, which will also remove incompatible cri-o
      command: dnf install -y runc --allowerasing

    - name: Install the newer cri-o 
      command: yum install -y cri-o cri-tools

    - name: Start cri-o service
      command: systemctl enable --now crio

    - name: Install Docker CE
      command: dnf install -y docker-ce
