#
# *If* your ntp is required to use a local pool server (e.g., DC firewall is blocking
# full access to port 123) then use this playbook to configure a chosen set of servers
# and to perform an initial possible large step sync to them.
#
---
- hosts: '{{ playhosts | default("k8s-cluster") }}'
  vars_files:
    - "vars.yml"

  gather_facts: False
  roles:
    - { role: ais_ntp }