apiVersion: v1
kind: Pod
metadata:
  name: ${POD_NAME}
  labels:
    app: ais
    type: aistarget
spec:
  hostNetwork: true
  containers:
  - name: aisnode
    image: ${DOCKER_IMAGE}
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /v1/health?readiness
        port: ${PORT}
        scheme: ${PROTOCOL}
      initialDelaySeconds: 20
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /v1/health
        port: ${PORT}
        scheme: ${PROTOCOL}
      initialDelaySeconds: 20
      failureThreshold: 5
      periodSeconds: 10
    securityContext:
      # Required for hostport to operate, or implement a full pod security policy
      privileged: true
    env:
      - name: MY_NODE
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: AIS_NODE_ROLE
        value: "target"
    volumeMounts:
     - name: aws-credentials
       mountPath: /root/.aws/
     - name: ais-persistent-fs
       mountPath: /usr/nvidia/data
     - name: ais-fs
       mountPath: /tmp/ais
     - name: ais-tls-certs
       mountPath: /var/certs
    ports:
      - containerPort: ${PORT}
        protocol: TCP
    command: ["bash","-c"]
    # TODO: fix the workaround of AIS_FS_PATHS
    args:
      - export PORT=${PORT} &&
        export PORT_INTRA_CONTROL=${PORT_INTRA_CONTROL} &&
        export PORT_INTRA_DATA=${PORT_INTRA_DATA} &&
        export AIS_FS_PATHS=${AIS_FS_PATHS} &&
        export AIS_PRIMARY_URL=${AIS_PRIMARY_URL} &&
        export HOSTNAME_LIST=${HOSTNAME_LIST} &&
        export TEST_FSPATH_COUNT=${TEST_FSPATH_COUNT} &&
        export AIS_BACKEND_PROVIDERS="${AIS_BACKEND_PROVIDERS}" &&
        export AIS_CONF_FILE=/etc/ais/ais.json &&
        export AIS_LOCAL_CONF_FILE=/etc/ais/ais_local.json &&
        export STATSD_CONF_FILE="/etc/ais/statsd.conf" &&
        export COLLECTD_CONF_FILE="/etc/ais/collectd.conf" &&
        export INSTANCE=${INSTANCE} &&
        export AIS_LOG_DIR=${AIS_LOG_DIR} &&
        export AIS_USE_HTTPS=${AIS_USE_HTTPS} &&
        export AIS_SKIP_VERIFY_CRT=${AIS_SKIP_VERIFY_CRT} &&
        export AIS_SERVER_CRT=${AIS_SERVER_CRT} &&
        export AIS_SERVER_KEY=${AIS_SERVER_KEY} &&
        source /etc/ais/utils.sh &&
        source /etc/ais/aisnode_config.sh &&
        aisnode -config=/etc/ais/ais.json -local_config=/etc/ais/ais_local.json -role=target;
  volumes:
    - name: aws-credentials
      secret:
        secretName: aws-credentials
        optional: true
    - name: ais-persistent-fs
      hostPath:
        path: /tmp/ais
        type: Directory
    - name: ais-fs
      hostPath:
        path: /tmp/ais
        type: Directory
    - name: ais-tls-certs
      secret:
        secretName: ais-tls-certs
        optional: true
